import type { Product } from "@/lib/types"

export const products: Product[] = [
  {
    id: "1",
    name: "Classic White T-Shirt",
    price: 29.99,
    description: "A timeless white t-shirt made from premium cotton for everyday comfort.",
    image: "/placeholder.svg?height=300&width=300",
    category: "clothing",
  },
  {
    id: "2",
    name: "Slim Fit Jeans",
    price: 59.99,
    description: "Modern slim fit jeans with a comfortable stretch for all-day wear.",
    image: "/placeholder.svg?height=300&width=300",
    category: "clothing",
  },
  {
    id: "3",
    name: "Leather Sneakers",
    price: 89.99,
    description: "Minimalist leather sneakers that go with everything in your wardrobe.",
    image: "/placeholder.svg?height=300&width=300",
    category: "footwear",
  },
  {
    id: "4",
    name: "Wool Blend Sweater",
    price: 79.99,
    description: "A cozy wool blend sweater perfect for cooler days.",
    image: "/placeholder.svg?height=300&width=300",
    category: "clothing",
  },
  {
    id: "5",
    name: "Canvas Backpack",
    price: 49.99,
    description: "Durable canvas backpack with multiple compartments for everyday use.",
    image: "/placeholder.svg?height=300&width=300",
    category: "accessories",
  },
  {
    id: "6",
    name: "Aviator Sunglasses",
    price: 129.99,
    description: "Classic aviator sunglasses with UV protection and polarized lenses.",
    image: "/placeholder.svg?height=300&width=300",
    category: "accessories",
  },
  {
    id: "7",
    name: "Denim Jacket",
    price: 89.99,
    description: "Versatile denim jacket that never goes out of style.",
    image: "/placeholder.svg?height=300&width=300",
    category: "clothing",
  },
  {
    id: "8",
    name: "Leather Belt",
    price: 39.99,
    description: "Premium leather belt with a classic buckle design.",
    image: "/placeholder.svg?height=300&width=300",
    category: "accessories",
  },
  {
    id: "9",
    name: "Cashmere Scarf",
    price: 69.99,
    description: "Luxuriously soft cashmere scarf to keep you warm in style.",
    image: "/placeholder.svg?height=300&width=300",
    category: "accessories",
  },
  {
    id: "10",
    name: "Striped Button-Up Shirt",
    price: 54.99,
    description: "A versatile striped button-up shirt for both casual and formal occasions.",
    image: "/placeholder.svg?height=300&width=300",
    category: "clothing",
  },
  {
    id: "11",
    name: "Leather Wallet",
    price: 45.99,
    description: "Compact leather wallet with multiple card slots and a bill compartment.",
    image: "/placeholder.svg?height=300&width=300",
    category: "accessories",
  },
  {
    id: "12",
    name: "Knit Beanie",
    price: 24.99,
    description: "Warm knit beanie perfect for cold weather days.",
    image: "/placeholder.svg?height=300&width=300",
    category: "accessories",
  },
]
